services:
  application:
    build:
      context: ./
      target: local
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN
    image: application-dev
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www/html:delegated
      - /var/www/html/node_modules
    entrypoint:
      - bash
      - -c
      - |
        set -e
        php artisan optimize:clear
        php artisan --host=0.0.0.0 --port=8080 serve
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:5.7
    command: [
      --character-set-server=utf8,
      --innodb-strict-mode=0,
      --innodb-file-format=barracuda,
      --innodb-file-per-table=1,
      --innodb-large-prefix=1
    ]
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Taipei
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      retries: 3
      timeout: 5s

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.210.0.0/16
